#!/usr/bin/perl
# unstruct - convert structured blocks of text into plain lines
#
# Copyright (C) 2026 TheMaither <themaither@gmail.com>
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 

use warnings;
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");

my $VERSION = '0.2';

#
# Processing arguments
#

sub show_usage
{
  print <<EOF
Usage: unstruct [OPTION]...

  -h, --help
                  show this message.
  -v, --version
                  show program version.

  -S, --start-pattern
                  regular expression for
                  struct start.
                  default is '^{$'.


  -E, --end-pattern
                  set regular expression for
                  struct end.
                  default is '^}$'.

EOF
}

sub show_version
{
  print <<EOF
unstruct (Text Processing Tools) $VERSION
Copyright (C) 2026 TheMaither <themaither\@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
EOF
}

sub error
{
  print $0, ': ', shift, "\n";
  die;
}

my $start_pattern = qr/^{$/;
my $end_pattern = qr/^}$/;

{
  my $help;
  my $version;
  my $from_file;

  GetOptions (
    'help|h' => \$help,
    'version|v' => \$version,
    'start-pattern|S=s' => \$start_pattern,
    'end-pattern|E=s' => \$end_pattern
  );
  show_usage and exit if defined $help;
  show_version and exit if defined $version;
}

#
# Doing actual work
#

my $prev;
my $deepness = 0;

while (<STDIN>)
{
  chomp $_;
  if (/$start_pattern/)
  {
    $deepness++;
    for (;;)
    {
      $_ = <STDIN>;
      chomp $_;
      if (/$end_pattern/)
      {
        $deepness--;
        last if $deepness == 0;
      }
      elsif (/$start_pattern/)
      {
        $deepness++;
      }
      print "$prev $_\n";
    }
    $prev = undef;
  }
  else
  {
    print "$prev\n" if $prev;
    $prev = $_;
  }
}
print "$prev\n" if $prev;

